---
- hosts: all
  tasks:

  - name: install apache2 package on Ubuntu
    apt:
     name: apache2
     update_cache: yes
     state: latest
    when: ansible_distribution == "Ubuntu"  
  
  

  - name: Install apache package on Redhat
    when: ansible_distribution == "RedHat"
    yum:
      update_cache: yes
      state: latest
      name: httpd
      name: php 
        
